// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, NativeStream, NativeStreamEndpoint, NativeStreamHandle, NativeStreamSession, PluginDependencies, RequestCapability, RuntimeFailure, StreamCapability, StreamEvent};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.http.stream-endpoint@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:d68c5e12dc319b6416eaba6592bd026784a100c0b29ef4adaeed3d13efaa9d25";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const STREAM_ENDPOINT_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const STREAM_ENDPOINT_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const STREAM_ENDPOINT_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const STREAM_ENDPOINT_CONTRACT: CapabilityReference<StreamEndpointClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_stream_endpoint { () => { "{\"capability_id\":\"lenso.http.stream-endpoint@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"describe_stream\",\"handle_stream\"],\"operation_kinds\":{\"handle_stream\":\"stream\"},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_stream_endpoint_client {
    () => { "{\"capability_id\":\"lenso.http.stream-endpoint@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.http.stream-endpoint@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_stream_endpoint_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.http.stream-endpoint@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_stream_endpoint_client {
    () => { "{\"capability_id\":\"lenso.http.stream-endpoint@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.http.stream-endpoint@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const DESCRIBE_STREAM_OPERATION: &str = "describe_stream";
pub const HANDLE_STREAM_OPERATION: &str = "handle_stream";

pub use lenso_contract_runtime::{Bytes, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeStreamRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeStreamResponse {
    #[serde(rename = "routes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub routes: Vec<DescribeStreamResponseRoutesItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeStreamResponseRoutesItem {
    #[serde(rename = "method")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub method: String,
    #[serde(rename = "path")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub path: String,
    #[serde(rename = "route_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub route_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DescribeStreamError {
    InvalidConfiguration,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HandleStreamRequest {
    #[serde(rename = "body")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body: Bytes,
    #[serde(rename = "credential")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub credential: Option<HandleStreamRequestCredential>,
    #[serde(rename = "headers")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub headers: Vec<HandleStreamRequestHeadersItem>,
    #[serde(rename = "method")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub method: String,
    #[serde(rename = "path")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub path: String,
    #[serde(rename = "path_parameters")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub path_parameters: Vec<HandleStreamRequestPathParametersItem>,
    #[serde(rename = "query")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "route_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub route_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HandleStreamRequestCredential {
    #[serde(rename = "scheme")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scheme: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HandleStreamRequestHeadersItem {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HandleStreamRequestPathParametersItem {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HandleStreamResponse {
    #[serde(rename = "body")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<Bytes>,
    #[serde(rename = "headers")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub headers: Option<Vec<HandleStreamResponseHeadersItem>>,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: HandleStreamResponseKind,
    #[serde(rename = "status")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HandleStreamResponseHeadersItem {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum HandleStreamResponseKind {
    #[serde(rename = "head")]
    Head,
    #[serde(rename = "chunk")]
    Chunk,
}

#[derive(Clone, Debug, PartialEq)]
pub enum HandleStreamError {
    Rejected,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct StreamEndpointDescribeStream;
impl RequestCapability for StreamEndpointDescribeStream {
    type Request = DescribeStreamRequest;
    type Response = DescribeStreamResponse;
    type DomainError = DescribeStreamError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DESCRIBE_STREAM_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<StreamEndpointRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).describe_stream(context, request)
    }
}

#[derive(Debug)]
pub struct StreamEndpointHandleStream;
pub type StreamEndpointHandleStreamEvent = StreamEvent<HandleStreamResponse, HandleStreamError>;
impl StreamCapability for StreamEndpointHandleStream {
    type OpenRequest = HandleStreamRequest;
    type Message = HandleStreamResponse;
    type DomainError = HandleStreamError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

impl serde::Serialize for DescribeStreamError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidConfiguration => serializer.serialize_str("invalid_configuration"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DescribeStreamError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_configuration" => Ok(Self::InvalidConfiguration),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for HandleStreamError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Rejected => serializer.serialize_str("rejected"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for HandleStreamError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "rejected" => Ok(Self::Rejected),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_describe_stream_request(value: &DescribeStreamRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_stream_request(wire: &str) -> Result<DescribeStreamRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_describe_stream_response(value: &DescribeStreamResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_stream_response(wire: &str) -> Result<DescribeStreamResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_describe_stream_error(value: &DescribeStreamError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_stream_error(wire: &str) -> Result<DescribeStreamError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_handle_stream_request(value: &HandleStreamRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_handle_stream_request(wire: &str) -> Result<HandleStreamRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_handle_stream_response(value: &HandleStreamResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_handle_stream_response(wire: &str) -> Result<HandleStreamResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_handle_stream_error(value: &HandleStreamError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_handle_stream_error(wire: &str) -> Result<HandleStreamError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoStreamEndpointDescribeStreamResult {
    fn __lenso_into_result(self) -> Result<Result<DescribeStreamResponse, DescribeStreamError>, RuntimeFailure>;
}
impl __LensoIntoStreamEndpointDescribeStreamResult for Result<DescribeStreamResponse, DescribeStreamError> {
    fn __lenso_into_result(self) -> Result<Result<DescribeStreamResponse, DescribeStreamError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoStreamEndpointDescribeStreamResult for Result<Result<DescribeStreamResponse, DescribeStreamError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DescribeStreamResponse, DescribeStreamError>, RuntimeFailure> { self }
}
impl __LensoIntoStreamEndpointDescribeStreamResult for Result<DescribeStreamResponse, lenso_plugin_authoring::PluginError<DescribeStreamError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DescribeStreamResponse, DescribeStreamError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoStreamEndpointDescribeStreamResult for Result<DescribeStreamResponse, StreamEndpointDescribeStreamInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DescribeStreamResponse, DescribeStreamError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(StreamEndpointDescribeStreamInvocationError::Domain(error)) => Ok(Err(error)),
            Err(StreamEndpointDescribeStreamInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoStreamEndpointHandleStreamStreamResult {
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, StreamEndpointHandleStreamInvocationError>;
}
impl<S> __LensoIntoStreamEndpointHandleStreamStreamResult for Result<S, HandleStreamError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, StreamEndpointHandleStreamInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
            .map_err(StreamEndpointHandleStreamInvocationError::Domain)
    }
}
impl<S> __LensoIntoStreamEndpointHandleStreamStreamResult for Result<S, lenso_plugin_authoring::PluginError<HandleStreamError, RuntimeFailure>>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, StreamEndpointHandleStreamInvocationError> {
        match self {
            Ok(stream) => Ok(Box::new(stream) as Box<dyn NativeStreamSession>),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Err(StreamEndpointHandleStreamInvocationError::Domain(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(StreamEndpointHandleStreamInvocationError::Runtime(error)),
        }
    }
}
impl<S> __LensoIntoStreamEndpointHandleStreamStreamResult for Result<S, StreamEndpointHandleStreamInvocationError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, StreamEndpointHandleStreamInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
    }
}

pub trait StreamEndpointProvider: fmt::Debug + 'static {
    fn describe_stream(&self, context: InvocationContext, request: DescribeStreamRequest) -> NativeRequestFuture<StreamEndpointDescribeStream>;
    fn handle_stream(&self, context: InvocationContext, request: HandleStreamRequest) -> LocalBoxFuture<'static, Result<Box<dyn NativeStreamSession>, StreamEndpointHandleStreamInvocationError>>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_stream_endpoint {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportStreamEndpoint;
        impl $crate::StreamEndpointProvider for $plugin {
        fn describe_stream(&self, context: __LensoNativeSupportStreamEndpoint::InvocationContext, request: $crate::DescribeStreamRequest) -> __LensoNativeSupportStreamEndpoint::NativeRequestFuture<$crate::StreamEndpointDescribeStream> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::describe_stream(&plugin, context, request).await;
                $crate::__LensoIntoStreamEndpointDescribeStreamResult::__lenso_into_result(result)
            })
        }
        fn handle_stream(&self, context: __LensoNativeSupportStreamEndpoint::InvocationContext, request: $crate::HandleStreamRequest) -> __LensoNativeSupportStreamEndpoint::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportStreamEndpoint::NativeStreamSession>, $crate::StreamEndpointHandleStreamInvocationError>> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::handle_stream(&plugin, context, request).await;
                $crate::__LensoIntoStreamEndpointHandleStreamStreamResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_stream_endpoint {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportStreamEndpoint;
        impl $crate::StreamEndpointProvider for $object {
        fn describe_stream(&self, context: __LensoNativeSupportStreamEndpoint::InvocationContext, request: $crate::DescribeStreamRequest) -> __LensoNativeSupportStreamEndpoint::NativeRequestFuture<$crate::StreamEndpointDescribeStream> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::describe_stream(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoStreamEndpointDescribeStreamResult::__lenso_into_result(result)
            })
        }
        fn handle_stream(&self, context: __LensoNativeSupportStreamEndpoint::InvocationContext, request: $crate::HandleStreamRequest) -> __LensoNativeSupportStreamEndpoint::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportStreamEndpoint::NativeStreamSession>, $crate::StreamEndpointHandleStreamInvocationError>> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get().map_err($crate::StreamEndpointHandleStreamInvocationError::Runtime)?;
                let result = <$plugin>::handle_stream(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoStreamEndpointHandleStreamStreamResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_stream_endpoint {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportStreamEndpoint;
        impl $crate::StreamEndpointProvider for $object {
        fn describe_stream(&self, context: __LensoNativeSupportStreamEndpoint::InvocationContext, request: $crate::DescribeStreamRequest) -> __LensoNativeSupportStreamEndpoint::NativeRequestFuture<$crate::StreamEndpointDescribeStream> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::StreamEndpointProvider>::describe_stream(plugin.as_ref(), context, request).await
            })
        }
        fn handle_stream(&self, context: __LensoNativeSupportStreamEndpoint::InvocationContext, request: $crate::HandleStreamRequest) -> __LensoNativeSupportStreamEndpoint::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportStreamEndpoint::NativeStreamSession>, $crate::StreamEndpointHandleStreamInvocationError>> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get().map_err($crate::StreamEndpointHandleStreamInvocationError::Runtime)?;
                <$plugin as $crate::StreamEndpointProvider>::handle_stream(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct StreamEndpointRequestEndpoint { provider: Rc<dyn StreamEndpointProvider> }

#[derive(Debug)]
pub struct StreamEndpointEndpoint<P: StreamEndpointProvider> { provider: Rc<P>, request_endpoint: StreamEndpointRequestEndpoint }
impl<P: StreamEndpointProvider> StreamEndpointEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn StreamEndpointProvider> = provider.clone();
        Self { provider, request_endpoint: StreamEndpointRequestEndpoint { provider: request_provider } }
    }
}

impl<P: StreamEndpointProvider> NativeRequestEndpoint for StreamEndpointEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        DESCRIBE_STREAM_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            DESCRIBE_STREAM_OPERATION => {
                let Ok(request) = request.downcast::<DescribeStreamRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).describe_stream(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

impl<P: StreamEndpointProvider> NativeStreamEndpoint for StreamEndpointEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        HANDLE_STREAM_OPERATION,
    ] }
    fn open(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn NativeStreamSession>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            HANDLE_STREAM_OPERATION => {
                let Ok(request) = request.downcast::<HandleStreamRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.handle_stream(context, *request).await {
                        Ok(value) => Ok(Ok(value as Box<dyn NativeStreamSession>)),
                        Err(StreamEndpointHandleStreamInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(StreamEndpointHandleStreamInvocationError::Runtime(error)) => Err(error),
                    }
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_stream_endpoint {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::StreamEndpointEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeStreamEndpoint>],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_stream_endpoint {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_stream_endpoint!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct StreamEndpointClient {
    describe_stream: NativeRequestHandle<StreamEndpointDescribeStream>,
    handle_stream: NativeStreamHandle<StreamEndpointHandleStream>,
}
impl StreamEndpointClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn describe_stream(&self, request: DescribeStreamRequest) -> Result<DescribeStreamResponse, StreamEndpointDescribeStreamInvocationError> {
        self.describe_stream.invoke(DESCRIBE_STREAM_OPERATION, request).await
            .map_err(StreamEndpointDescribeStreamInvocationError::Runtime)?
            .map_err(StreamEndpointDescribeStreamInvocationError::Domain)
    }

    pub async fn describe_stream_with_context(&self, context: InvocationContext, request: DescribeStreamRequest) -> Result<DescribeStreamResponse, StreamEndpointDescribeStreamInvocationError> {
        self.describe_stream.invoke_with_context(DESCRIBE_STREAM_OPERATION, context, request).await
            .map_err(StreamEndpointDescribeStreamInvocationError::Runtime)?
            .map_err(StreamEndpointDescribeStreamInvocationError::Domain)
    }

    pub async fn handle_stream(&self, request: HandleStreamRequest) -> Result<NativeStream<StreamEndpointHandleStream>, StreamEndpointHandleStreamInvocationError> {
        self.handle_stream.open(HANDLE_STREAM_OPERATION, request).await
            .map_err(StreamEndpointHandleStreamInvocationError::Runtime)?
            .map_err(StreamEndpointHandleStreamInvocationError::Domain)
    }

    pub async fn handle_stream_with_context(&self, context: InvocationContext, request: HandleStreamRequest) -> Result<NativeStream<StreamEndpointHandleStream>, StreamEndpointHandleStreamInvocationError> {
        self.handle_stream.open_with_context(HANDLE_STREAM_OPERATION, context, request).await
            .map_err(StreamEndpointHandleStreamInvocationError::Runtime)?
            .map_err(StreamEndpointHandleStreamInvocationError::Domain)
    }
}

impl CapabilityClient for StreamEndpointClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            describe_stream: dependencies.one::<StreamEndpointDescribeStream>()?,
            handle_stream: dependencies.one_stream::<StreamEndpointHandleStream>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for StreamEndpointClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    describe_stream: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<StreamEndpointDescribeStream>()?,
                    handle_stream: binding.stream_handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<StreamEndpointHandleStream>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum StreamEndpointDescribeStreamInvocationError {
    Domain(DescribeStreamError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum StreamEndpointHandleStreamInvocationError {
    Domain(HandleStreamError),
    Runtime(RuntimeFailure),
}
