// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, RuntimeFailure, NativeRequestEndpoint, NativeRequestHandle, RequestCapability};

pub const CAPABILITY_ID: &str = "lenso.web.shell@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const SHELL_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const SHELL_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

pub const READ_ASSET_OPERATION: &str = "read_asset";
pub const RENDER_ROUTE_OPERATION: &str = "render_route";

pub type Int64 = String;
pub type Uint64 = String;
pub type Bytes = String;
pub type Timestamp = String;
pub type Duration = String;
pub type OptionalValue<T> = Option<Option<T>>;

#[allow(dead_code)]
fn deserialize_required<'de, D, T>(deserializer: D) -> Result<T, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    <T as serde::Deserialize>::deserialize(deserializer)
}

#[allow(dead_code, clippy::option_option)]
fn deserialize_optional_value<'de, D, T>(deserializer: D) -> Result<Option<Option<T>>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    Ok(Some(<Option<T> as serde::Deserialize>::deserialize(deserializer)?))
}

#[allow(dead_code)]
fn validate_portable_json_value(value: &serde_json::Value) -> Result<(), String> {
    match value {
        serde_json::Value::Number(number) => {
            let safe = number.as_i64().is_some_and(|value| (-9_007_199_254_740_991..=9_007_199_254_740_991).contains(&value))
                || number.as_u64().is_some_and(|value| value <= 9_007_199_254_740_991)
                || (number.is_f64() && number.as_f64().is_some_and(|value| value.is_finite() && (value.abs() <= 9_007_199_254_740_991.0 || value.fract() != 0.0)));
            if !safe {
                return Err("wire JSON contains an unsafe number".to_owned());
            }
        }
        serde_json::Value::Array(values) => {
            for value in values {
                validate_portable_json_value(value)?;
            }
        }
        serde_json::Value::Object(values) => {
            for value in values.values() {
                validate_portable_json_value(value)?;
            }
        }
        serde_json::Value::Null | serde_json::Value::Bool(_) | serde_json::Value::String(_) => {}
    }
    Ok(())
}

#[allow(dead_code)]
fn portable_json_error(detail: String) -> serde_json::Error {
    serde_json::Error::io(std::io::Error::new(std::io::ErrorKind::InvalidData, detail))
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UnknownDomainError {
    pub code: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<serde_json::Value>,
    #[serde(default, flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadAssetRequest {
    #[serde(rename = "path")]
    #[serde(deserialize_with = "deserialize_required")]
    pub path: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadAssetResponse {
    #[serde(rename = "content")]
    #[serde(deserialize_with = "deserialize_required")]
    pub content: String,
    #[serde(rename = "content_type")]
    #[serde(deserialize_with = "deserialize_required")]
    pub content_type: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadAssetError {
    AssetNotFound,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenderRouteRequest {
    #[serde(rename = "path")]
    #[serde(deserialize_with = "deserialize_required")]
    pub path: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenderRouteResponse {
    #[serde(rename = "asset_paths")]
    #[serde(deserialize_with = "deserialize_required")]
    pub asset_paths: Vec<String>,
    #[serde(rename = "body")]
    #[serde(deserialize_with = "deserialize_required")]
    pub body: String,
    #[serde(rename = "contribution_id")]
    #[serde(deserialize_with = "deserialize_required")]
    pub contribution_id: String,
    #[serde(rename = "navigation")]
    #[serde(deserialize_with = "deserialize_required")]
    pub navigation: Vec<RenderRouteResponseNavigationItem>,
    #[serde(rename = "requirements")]
    #[serde(deserialize_with = "deserialize_required")]
    pub requirements: Vec<RenderRouteResponseRequirementsItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenderRouteResponseNavigationItem {
    #[serde(rename = "label")]
    #[serde(deserialize_with = "deserialize_required")]
    pub label: String,
    #[serde(rename = "route")]
    #[serde(deserialize_with = "deserialize_required")]
    pub route: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenderRouteResponseRequirementsItem {
    #[serde(rename = "capability_id")]
    #[serde(deserialize_with = "deserialize_required")]
    pub capability_id: String,
    #[serde(rename = "descriptor_version")]
    #[serde(deserialize_with = "deserialize_required")]
    pub descriptor_version: String,
    #[serde(rename = "operations")]
    #[serde(deserialize_with = "deserialize_required")]
    pub operations: Vec<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RenderRouteError {
    RouteNotFound,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ShellReadAsset;
impl RequestCapability for ShellReadAsset {
    type Request = ReadAssetRequest;
    type Response = ReadAssetResponse;
    type DomainError = ReadAssetError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

#[derive(Debug)]
pub struct ShellRenderRoute;
impl RequestCapability for ShellRenderRoute {
    type Request = RenderRouteRequest;
    type Response = RenderRouteResponse;
    type DomainError = RenderRouteError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

impl serde::Serialize for ReadAssetError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AssetNotFound => serializer.serialize_str("asset_not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadAssetError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "asset_not_found" => Ok(Self::AssetNotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RenderRouteError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::RouteNotFound => serializer.serialize_str("route_not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RenderRouteError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "route_not_found" => Ok(Self::RouteNotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_read_asset_request(value: &ReadAssetRequest) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_read_asset_request(wire: &str) -> Result<ReadAssetRequest, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }
pub fn encode_read_asset_response(value: &ReadAssetResponse) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_read_asset_response(wire: &str) -> Result<ReadAssetResponse, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }
pub fn encode_read_asset_error(value: &ReadAssetError) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_read_asset_error(wire: &str) -> Result<ReadAssetError, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }

pub fn encode_render_route_request(value: &RenderRouteRequest) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_render_route_request(wire: &str) -> Result<RenderRouteRequest, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }
pub fn encode_render_route_response(value: &RenderRouteResponse) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_render_route_response(wire: &str) -> Result<RenderRouteResponse, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }
pub fn encode_render_route_error(value: &RenderRouteError) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_render_route_error(wire: &str) -> Result<RenderRouteError, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }

pub trait ShellProvider: fmt::Debug + 'static {
    fn read_asset(&self, context: InvocationContext, request: ReadAssetRequest) -> LocalBoxFuture<'static, Result<ReadAssetResponse, ShellReadAssetInvocationError>>;
    fn render_route(&self, context: InvocationContext, request: RenderRouteRequest) -> LocalBoxFuture<'static, Result<RenderRouteResponse, ShellRenderRouteInvocationError>>;
}

#[derive(Debug)]
pub struct ShellEndpoint<P> { provider: Rc<P> }
impl<P: ShellProvider> ShellEndpoint<P> {
    pub fn new(provider: P) -> Self { Self { provider: Rc::new(provider) } }
}

impl<P: ShellProvider> NativeRequestEndpoint for ShellEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        READ_ASSET_OPERATION,
        RENDER_ROUTE_OPERATION,
    ] }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            READ_ASSET_OPERATION => {
                let Ok(request) = request.downcast::<ReadAssetRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.read_asset(context, *request).await {
                        Ok(value) => Ok(Ok(Box::new(value) as Box<dyn std::any::Any>)),
                        Err(ShellReadAssetInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(ShellReadAssetInvocationError::Runtime(error)) => Err(error),
                    }
                })
            },
            RENDER_ROUTE_OPERATION => {
                let Ok(request) = request.downcast::<RenderRouteRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.render_route(context, *request).await {
                        Ok(value) => Ok(Ok(Box::new(value) as Box<dyn std::any::Any>)),
                        Err(ShellRenderRouteInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(ShellRenderRouteInvocationError::Runtime(error)) => Err(error),
                    }
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[derive(Debug)]
pub struct ShellClient {
    read_asset: NativeRequestHandle<ShellReadAsset>,
    render_route: NativeRequestHandle<ShellRenderRoute>,
}
impl ShellClient {
    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            read_asset: dependencies.one::<ShellReadAsset>()?,
            render_route: dependencies.one::<ShellRenderRoute>()?,
        })
    }

    pub async fn read_asset(&self, request: ReadAssetRequest) -> Result<ReadAssetResponse, ShellReadAssetInvocationError> {
        self.read_asset.invoke(READ_ASSET_OPERATION, request).await
            .map_err(ShellReadAssetInvocationError::Runtime)?
            .map_err(ShellReadAssetInvocationError::Domain)
    }

    pub async fn read_asset_with_context(&self, context: InvocationContext, request: ReadAssetRequest) -> Result<ReadAssetResponse, ShellReadAssetInvocationError> {
        self.read_asset.invoke_with_context(READ_ASSET_OPERATION, context, request).await
            .map_err(ShellReadAssetInvocationError::Runtime)?
            .map_err(ShellReadAssetInvocationError::Domain)
    }

    pub async fn render_route(&self, request: RenderRouteRequest) -> Result<RenderRouteResponse, ShellRenderRouteInvocationError> {
        self.render_route.invoke(RENDER_ROUTE_OPERATION, request).await
            .map_err(ShellRenderRouteInvocationError::Runtime)?
            .map_err(ShellRenderRouteInvocationError::Domain)
    }

    pub async fn render_route_with_context(&self, context: InvocationContext, request: RenderRouteRequest) -> Result<RenderRouteResponse, ShellRenderRouteInvocationError> {
        self.render_route.invoke_with_context(RENDER_ROUTE_OPERATION, context, request).await
            .map_err(ShellRenderRouteInvocationError::Runtime)?
            .map_err(ShellRenderRouteInvocationError::Domain)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShellReadAssetInvocationError {
    Domain(ReadAssetError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ShellRenderRouteInvocationError {
    Domain(RenderRouteError),
    Runtime(RuntimeFailure),
}
