// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, RuntimeFailure, NativeRequestEndpoint, NativeRequestHandle, RequestCapability};

pub const CAPABILITY_ID: &str = "lenso.ui.contribution@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const CONTRIBUTION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const CONTRIBUTION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

pub const DESCRIBE_OPERATION: &str = "describe";

pub type Int64 = String;
pub type Uint64 = String;
pub type Bytes = String;
pub type Timestamp = String;
pub type Duration = String;
pub type OptionalValue<T> = Option<Option<T>>;

#[allow(dead_code)]
fn deserialize_required<'de, D, T>(deserializer: D) -> Result<T, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    <T as serde::Deserialize>::deserialize(deserializer)
}

#[allow(dead_code, clippy::option_option)]
fn deserialize_optional_value<'de, D, T>(deserializer: D) -> Result<Option<Option<T>>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    Ok(Some(<Option<T> as serde::Deserialize>::deserialize(deserializer)?))
}

#[allow(dead_code)]
fn validate_portable_json_value(value: &serde_json::Value) -> Result<(), String> {
    match value {
        serde_json::Value::Number(number) => {
            let safe = number.as_i64().is_some_and(|value| (-9_007_199_254_740_991..=9_007_199_254_740_991).contains(&value))
                || number.as_u64().is_some_and(|value| value <= 9_007_199_254_740_991)
                || (number.is_f64() && number.as_f64().is_some_and(|value| value.is_finite() && (value.abs() <= 9_007_199_254_740_991.0 || value.fract() != 0.0)));
            if !safe {
                return Err("wire JSON contains an unsafe number".to_owned());
            }
        }
        serde_json::Value::Array(values) => {
            for value in values {
                validate_portable_json_value(value)?;
            }
        }
        serde_json::Value::Object(values) => {
            for value in values.values() {
                validate_portable_json_value(value)?;
            }
        }
        serde_json::Value::Null | serde_json::Value::Bool(_) | serde_json::Value::String(_) => {}
    }
    Ok(())
}

#[allow(dead_code)]
fn portable_json_error(detail: String) -> serde_json::Error {
    serde_json::Error::io(std::io::Error::new(std::io::ErrorKind::InvalidData, detail))
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UnknownDomainError {
    pub code: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<serde_json::Value>,
    #[serde(default, flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeResponse {
    #[serde(rename = "assets")]
    #[serde(deserialize_with = "deserialize_required")]
    pub assets: Vec<DescribeResponseAssetsItem>,
    #[serde(rename = "body")]
    #[serde(deserialize_with = "deserialize_required")]
    pub body: String,
    #[serde(rename = "contribution_id")]
    #[serde(deserialize_with = "deserialize_required")]
    pub contribution_id: String,
    #[serde(rename = "navigation_label")]
    #[serde(deserialize_with = "deserialize_required")]
    pub navigation_label: String,
    #[serde(rename = "requirements")]
    #[serde(deserialize_with = "deserialize_required")]
    pub requirements: Vec<DescribeResponseRequirementsItem>,
    #[serde(rename = "route")]
    #[serde(deserialize_with = "deserialize_required")]
    pub route: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeResponseAssetsItem {
    #[serde(rename = "content")]
    #[serde(deserialize_with = "deserialize_required")]
    pub content: String,
    #[serde(rename = "content_type")]
    #[serde(deserialize_with = "deserialize_required")]
    pub content_type: String,
    #[serde(rename = "path")]
    #[serde(deserialize_with = "deserialize_required")]
    pub path: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeResponseRequirementsItem {
    #[serde(rename = "capability_id")]
    #[serde(deserialize_with = "deserialize_required")]
    pub capability_id: String,
    #[serde(rename = "descriptor_version")]
    #[serde(deserialize_with = "deserialize_required")]
    pub descriptor_version: String,
    #[serde(rename = "operations")]
    #[serde(deserialize_with = "deserialize_required")]
    pub operations: Vec<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DescribeError {
    MetadataUnavailable,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Contribution;
impl RequestCapability for Contribution {
    type Request = DescribeRequest;
    type Response = DescribeResponse;
    type DomainError = DescribeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

impl serde::Serialize for DescribeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::MetadataUnavailable => serializer.serialize_str("metadata_unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DescribeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "metadata_unavailable" => Ok(Self::MetadataUnavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_describe_request(value: &DescribeRequest) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_describe_request(wire: &str) -> Result<DescribeRequest, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }
pub fn encode_describe_response(value: &DescribeResponse) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_describe_response(wire: &str) -> Result<DescribeResponse, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }
pub fn encode_describe_error(value: &DescribeError) -> Result<String, serde_json::Error> { let value = serde_json::to_value(value)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::to_string(&value) }
pub fn decode_describe_error(wire: &str) -> Result<DescribeError, serde_json::Error> { let value: serde_json::Value = serde_json::from_str(wire)?; validate_portable_json_value(&value).map_err(portable_json_error)?; serde_json::from_value(value) }

pub trait ContributionProvider: fmt::Debug + 'static {
    fn describe(&self, context: InvocationContext, request: DescribeRequest) -> LocalBoxFuture<'static, Result<DescribeResponse, ContributionInvocationError>>;
}

#[derive(Debug)]
pub struct ContributionEndpoint<P> { provider: Rc<P> }
impl<P: ContributionProvider> ContributionEndpoint<P> {
    pub fn new(provider: P) -> Self { Self { provider: Rc::new(provider) } }
}

impl<P: ContributionProvider> NativeRequestEndpoint for ContributionEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        DESCRIBE_OPERATION,
    ] }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            DESCRIBE_OPERATION => {
                let Ok(request) = request.downcast::<DescribeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.describe(context, *request).await {
                        Ok(value) => Ok(Ok(Box::new(value) as Box<dyn std::any::Any>)),
                        Err(ContributionInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(ContributionInvocationError::Runtime(error)) => Err(error),
                    }
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[derive(Debug)]
pub struct ContributionClient {
    describe: NativeRequestHandle<Contribution>,
}
impl ContributionClient {
    pub fn new(handle: NativeRequestHandle<Contribution>) -> Self {
        Self { describe: handle }
    }

    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            describe: dependencies.one::<Contribution>()?,
        })
    }

    pub async fn describe(&self, request: DescribeRequest) -> Result<DescribeResponse, ContributionInvocationError> {
        self.describe.invoke(DESCRIBE_OPERATION, request).await
            .map_err(ContributionInvocationError::Runtime)?
            .map_err(ContributionInvocationError::Domain)
    }

    pub async fn describe_with_context(&self, context: InvocationContext, request: DescribeRequest) -> Result<DescribeResponse, ContributionInvocationError> {
        self.describe.invoke_with_context(DESCRIBE_OPERATION, context, request).await
            .map_err(ContributionInvocationError::Runtime)?
            .map_err(ContributionInvocationError::Domain)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ContributionInvocationError {
    Domain(DescribeError),
    Runtime(RuntimeFailure),
}
