// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, NativeStream, NativeStreamEndpoint, NativeStreamHandle, NativeStreamSession, PluginDependencies, RequestCapability, RuntimeFailure, StreamCapability, StreamEvent};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.websocket.endpoint@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:ab8584c9e3f1e1582398521cecedf0b2e9de0c6d29386141dcfc8175c620b798";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const ENDPOINT_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const ENDPOINT_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const ENDPOINT_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const ENDPOINT_CONTRACT: CapabilityReference<EndpointClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_endpoint { () => { "{\"capability_id\":\"lenso.websocket.endpoint@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"connect_websocket\",\"describe_websocket\"],\"operation_kinds\":{\"connect_websocket\":\"stream\"},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_endpoint_client {
    () => { "{\"capability_id\":\"lenso.websocket.endpoint@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.websocket.endpoint@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_endpoint_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.websocket.endpoint@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_endpoint_client {
    () => { "{\"capability_id\":\"lenso.websocket.endpoint@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.websocket.endpoint@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const CONNECT_WEBSOCKET_OPERATION: &str = "connect_websocket";
pub const DESCRIBE_WEBSOCKET_OPERATION: &str = "describe_websocket";

pub use lenso_contract_runtime::{Bytes, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ConnectWebsocketRequest {
    #[serde(rename = "credential")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub credential: Option<ConnectWebsocketRequestCredential>,
    #[serde(rename = "headers")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub headers: Vec<ConnectWebsocketRequestHeadersItem>,
    #[serde(rename = "path")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub path: String,
    #[serde(rename = "path_parameters")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub path_parameters: Vec<ConnectWebsocketRequestPathParametersItem>,
    #[serde(rename = "protocols")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub protocols: Vec<String>,
    #[serde(rename = "query")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "route_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub route_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ConnectWebsocketRequestCredential {
    #[serde(rename = "scheme")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scheme: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ConnectWebsocketRequestHeadersItem {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ConnectWebsocketRequestPathParametersItem {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ConnectWebsocketResponse {
    #[serde(rename = "body")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<Bytes>,
    #[serde(rename = "code")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<i64>,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: ConnectWebsocketResponseKind,
    #[serde(rename = "protocol")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    #[serde(rename = "reason")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "text")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ConnectWebsocketResponseKind {
    #[serde(rename = "accept")]
    Accept,
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "binary")]
    Binary,
    #[serde(rename = "close")]
    Close,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ConnectWebsocketError {
    Rejected,
    Unauthorized,
    UnsupportedProtocol,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeWebsocketRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeWebsocketResponse {
    #[serde(rename = "routes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub routes: Vec<DescribeWebsocketResponseRoutesItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeWebsocketResponseRoutesItem {
    #[serde(rename = "path")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub path: String,
    #[serde(rename = "route_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub route_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DescribeWebsocketError {
    InvalidConfiguration,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct EndpointConnectWebsocket;
pub type EndpointConnectWebsocketEvent = StreamEvent<ConnectWebsocketResponse, ConnectWebsocketError>;
impl StreamCapability for EndpointConnectWebsocket {
    type OpenRequest = ConnectWebsocketRequest;
    type Message = ConnectWebsocketResponse;
    type DomainError = ConnectWebsocketError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

#[derive(Debug)]
pub struct EndpointDescribeWebsocket;
impl RequestCapability for EndpointDescribeWebsocket {
    type Request = DescribeWebsocketRequest;
    type Response = DescribeWebsocketResponse;
    type DomainError = DescribeWebsocketError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DESCRIBE_WEBSOCKET_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<EndpointRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).describe_websocket(context, request)
    }
}

impl serde::Serialize for ConnectWebsocketError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Rejected => serializer.serialize_str("rejected"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::UnsupportedProtocol => serializer.serialize_str("unsupported_protocol"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ConnectWebsocketError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "rejected" => Ok(Self::Rejected),
                "unauthorized" => Ok(Self::Unauthorized),
                "unsupported_protocol" => Ok(Self::UnsupportedProtocol),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for DescribeWebsocketError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidConfiguration => serializer.serialize_str("invalid_configuration"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DescribeWebsocketError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_configuration" => Ok(Self::InvalidConfiguration),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_connect_websocket_request(value: &ConnectWebsocketRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_connect_websocket_request(wire: &str) -> Result<ConnectWebsocketRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_connect_websocket_response(value: &ConnectWebsocketResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_connect_websocket_response(wire: &str) -> Result<ConnectWebsocketResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_connect_websocket_error(value: &ConnectWebsocketError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_connect_websocket_error(wire: &str) -> Result<ConnectWebsocketError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_describe_websocket_request(value: &DescribeWebsocketRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_websocket_request(wire: &str) -> Result<DescribeWebsocketRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_describe_websocket_response(value: &DescribeWebsocketResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_websocket_response(wire: &str) -> Result<DescribeWebsocketResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_describe_websocket_error(value: &DescribeWebsocketError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_websocket_error(wire: &str) -> Result<DescribeWebsocketError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoEndpointConnectWebsocketStreamResult {
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, EndpointConnectWebsocketInvocationError>;
}
impl<S> __LensoIntoEndpointConnectWebsocketStreamResult for Result<S, ConnectWebsocketError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, EndpointConnectWebsocketInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
            .map_err(EndpointConnectWebsocketInvocationError::Domain)
    }
}
impl<S> __LensoIntoEndpointConnectWebsocketStreamResult for Result<S, lenso_plugin_authoring::PluginError<ConnectWebsocketError, RuntimeFailure>>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, EndpointConnectWebsocketInvocationError> {
        match self {
            Ok(stream) => Ok(Box::new(stream) as Box<dyn NativeStreamSession>),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Err(EndpointConnectWebsocketInvocationError::Domain(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(EndpointConnectWebsocketInvocationError::Runtime(error)),
        }
    }
}
impl<S> __LensoIntoEndpointConnectWebsocketStreamResult for Result<S, EndpointConnectWebsocketInvocationError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, EndpointConnectWebsocketInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
    }
}

#[doc(hidden)]
pub trait __LensoIntoEndpointDescribeWebsocketResult {
    fn __lenso_into_result(self) -> Result<Result<DescribeWebsocketResponse, DescribeWebsocketError>, RuntimeFailure>;
}
impl __LensoIntoEndpointDescribeWebsocketResult for Result<DescribeWebsocketResponse, DescribeWebsocketError> {
    fn __lenso_into_result(self) -> Result<Result<DescribeWebsocketResponse, DescribeWebsocketError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoEndpointDescribeWebsocketResult for Result<Result<DescribeWebsocketResponse, DescribeWebsocketError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DescribeWebsocketResponse, DescribeWebsocketError>, RuntimeFailure> { self }
}
impl __LensoIntoEndpointDescribeWebsocketResult for Result<DescribeWebsocketResponse, lenso_plugin_authoring::PluginError<DescribeWebsocketError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DescribeWebsocketResponse, DescribeWebsocketError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoEndpointDescribeWebsocketResult for Result<DescribeWebsocketResponse, EndpointDescribeWebsocketInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DescribeWebsocketResponse, DescribeWebsocketError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(EndpointDescribeWebsocketInvocationError::Domain(error)) => Ok(Err(error)),
            Err(EndpointDescribeWebsocketInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait EndpointProvider: fmt::Debug + 'static {
    fn connect_websocket(&self, context: InvocationContext, request: ConnectWebsocketRequest) -> LocalBoxFuture<'static, Result<Box<dyn NativeStreamSession>, EndpointConnectWebsocketInvocationError>>;
    fn describe_websocket(&self, context: InvocationContext, request: DescribeWebsocketRequest) -> NativeRequestFuture<EndpointDescribeWebsocket>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_endpoint {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportEndpoint;
        impl $crate::EndpointProvider for $plugin {
        fn connect_websocket(&self, context: __LensoNativeSupportEndpoint::InvocationContext, request: $crate::ConnectWebsocketRequest) -> __LensoNativeSupportEndpoint::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportEndpoint::NativeStreamSession>, $crate::EndpointConnectWebsocketInvocationError>> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::connect_websocket(&plugin, context, request).await;
                $crate::__LensoIntoEndpointConnectWebsocketStreamResult::__lenso_into_result(result)
            })
        }
        fn describe_websocket(&self, context: __LensoNativeSupportEndpoint::InvocationContext, request: $crate::DescribeWebsocketRequest) -> __LensoNativeSupportEndpoint::NativeRequestFuture<$crate::EndpointDescribeWebsocket> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::describe_websocket(&plugin, context, request).await;
                $crate::__LensoIntoEndpointDescribeWebsocketResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_endpoint {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportEndpoint;
        impl $crate::EndpointProvider for $object {
        fn connect_websocket(&self, context: __LensoNativeSupportEndpoint::InvocationContext, request: $crate::ConnectWebsocketRequest) -> __LensoNativeSupportEndpoint::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportEndpoint::NativeStreamSession>, $crate::EndpointConnectWebsocketInvocationError>> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get().map_err($crate::EndpointConnectWebsocketInvocationError::Runtime)?;
                let result = <$plugin>::connect_websocket(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoEndpointConnectWebsocketStreamResult::__lenso_into_result(result)
            })
        }
        fn describe_websocket(&self, context: __LensoNativeSupportEndpoint::InvocationContext, request: $crate::DescribeWebsocketRequest) -> __LensoNativeSupportEndpoint::NativeRequestFuture<$crate::EndpointDescribeWebsocket> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::describe_websocket(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoEndpointDescribeWebsocketResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_endpoint {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportEndpoint;
        impl $crate::EndpointProvider for $object {
        fn connect_websocket(&self, context: __LensoNativeSupportEndpoint::InvocationContext, request: $crate::ConnectWebsocketRequest) -> __LensoNativeSupportEndpoint::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportEndpoint::NativeStreamSession>, $crate::EndpointConnectWebsocketInvocationError>> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get().map_err($crate::EndpointConnectWebsocketInvocationError::Runtime)?;
                <$plugin as $crate::EndpointProvider>::connect_websocket(plugin.as_ref(), context, request).await
            })
        }
        fn describe_websocket(&self, context: __LensoNativeSupportEndpoint::InvocationContext, request: $crate::DescribeWebsocketRequest) -> __LensoNativeSupportEndpoint::NativeRequestFuture<$crate::EndpointDescribeWebsocket> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::EndpointProvider>::describe_websocket(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct EndpointRequestEndpoint { provider: Rc<dyn EndpointProvider> }

#[derive(Debug)]
pub struct EndpointEndpoint<P: EndpointProvider> { provider: Rc<P>, request_endpoint: EndpointRequestEndpoint }
impl<P: EndpointProvider> EndpointEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn EndpointProvider> = provider.clone();
        Self { provider, request_endpoint: EndpointRequestEndpoint { provider: request_provider } }
    }
}

impl<P: EndpointProvider> NativeRequestEndpoint for EndpointEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        DESCRIBE_WEBSOCKET_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            DESCRIBE_WEBSOCKET_OPERATION => {
                let Ok(request) = request.downcast::<DescribeWebsocketRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).describe_websocket(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

impl<P: EndpointProvider> NativeStreamEndpoint for EndpointEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CONNECT_WEBSOCKET_OPERATION,
    ] }
    fn open(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn NativeStreamSession>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CONNECT_WEBSOCKET_OPERATION => {
                let Ok(request) = request.downcast::<ConnectWebsocketRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.connect_websocket(context, *request).await {
                        Ok(value) => Ok(Ok(value as Box<dyn NativeStreamSession>)),
                        Err(EndpointConnectWebsocketInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(EndpointConnectWebsocketInvocationError::Runtime(error)) => Err(error),
                    }
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_endpoint {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::EndpointEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeStreamEndpoint>],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_endpoint {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_endpoint!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct EndpointClient {
    connect_websocket: NativeStreamHandle<EndpointConnectWebsocket>,
    describe_websocket: NativeRequestHandle<EndpointDescribeWebsocket>,
}
impl EndpointClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn connect_websocket(&self, request: ConnectWebsocketRequest) -> Result<NativeStream<EndpointConnectWebsocket>, EndpointConnectWebsocketInvocationError> {
        self.connect_websocket.open(CONNECT_WEBSOCKET_OPERATION, request).await
            .map_err(EndpointConnectWebsocketInvocationError::Runtime)?
            .map_err(EndpointConnectWebsocketInvocationError::Domain)
    }

    pub async fn connect_websocket_with_context(&self, context: InvocationContext, request: ConnectWebsocketRequest) -> Result<NativeStream<EndpointConnectWebsocket>, EndpointConnectWebsocketInvocationError> {
        self.connect_websocket.open_with_context(CONNECT_WEBSOCKET_OPERATION, context, request).await
            .map_err(EndpointConnectWebsocketInvocationError::Runtime)?
            .map_err(EndpointConnectWebsocketInvocationError::Domain)
    }

    pub async fn describe_websocket(&self, request: DescribeWebsocketRequest) -> Result<DescribeWebsocketResponse, EndpointDescribeWebsocketInvocationError> {
        self.describe_websocket.invoke(DESCRIBE_WEBSOCKET_OPERATION, request).await
            .map_err(EndpointDescribeWebsocketInvocationError::Runtime)?
            .map_err(EndpointDescribeWebsocketInvocationError::Domain)
    }

    pub async fn describe_websocket_with_context(&self, context: InvocationContext, request: DescribeWebsocketRequest) -> Result<DescribeWebsocketResponse, EndpointDescribeWebsocketInvocationError> {
        self.describe_websocket.invoke_with_context(DESCRIBE_WEBSOCKET_OPERATION, context, request).await
            .map_err(EndpointDescribeWebsocketInvocationError::Runtime)?
            .map_err(EndpointDescribeWebsocketInvocationError::Domain)
    }
}

impl CapabilityClient for EndpointClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            connect_websocket: dependencies.one_stream::<EndpointConnectWebsocket>()?,
            describe_websocket: dependencies.one::<EndpointDescribeWebsocket>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for EndpointClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    connect_websocket: binding.stream_handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<EndpointConnectWebsocket>()?,
                    describe_websocket: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<EndpointDescribeWebsocket>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum EndpointConnectWebsocketInvocationError {
    Domain(ConnectWebsocketError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum EndpointDescribeWebsocketInvocationError {
    Domain(DescribeWebsocketError),
    Runtime(RuntimeFailure),
}
